baseURL = "https://sanbika.github.io/"
title = "浆果丛林"
theme = "PaperMod"

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
    codeFences = true
    guessSyntax = false