[zh-cn]
  label = "中文"
  weight = 1
  title = "浆果丛林"
  [zh-cn.params]
    description = "浆果丛林 —— 个人主页与博客"

[en]
  label = "English"
  weight = 2
  title = "Berry Jungle"
  [en.params]
    description = "Berry Jungle — personal site and blog"
