[[main]]
  identifier = "search"
  name = "Search"
  url = "/en/search/"
  weight = 5

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "/en/posts/"
  weight = 10

[[main]]
  identifier = "projects"
  name = "Projects"
  url = "/en/projects/"
  weight = 20

[[main]]
  identifier = "about"
  name = "About"
  url = "/en/about/"
  weight = 30

[[main]]
  identifier = "rss"
  name = "RSS"
  url = "/en/index.xml"
  weight = 40